# Еще про Промисы

Обещания (promises) в JavaScript – это новый инструмент для работы с отложенными или асинхронными вычислениями, добавленный в ECMAScript 2015 (6-я версия ECMA-262).

До появления «обещаний» асинхронные задачи можно было решать с помощью функций обратного вызова или с помощью обработки событий.

В использовании функций обратного вызова есть существенный недостаток с точки зрения организации кода: "callback hell". 

Этот недостаток заключается в том, что в функции обратного вызова есть параметр, который, в свою очередь, также является функцией обратного вызова – и так может продолжаться до бесконечности.

![help](https://habrastorage.org/files/eb6/f44/e8d/eb6f44e8d7664f0f97fd5a4879daa16b.png)

Может образоваться несколько уровней таких вложенностей. 

Это приводит к плохому чтению кода и запутанности между вызовами функций обратного вызова. 

Это, в свою очередь, приведет к ошибкам. С такой структурой кода найти ошибки очень сложно.


# Состояния промисов

![help](https://habrastorage.org/webt/pk/hr/zz/pkhrzzgtdsgqvtptwn26gmtbjhk.png)

- Нерешенный или Ожидающий — Промис ожидает, если результат не готов. 

То есть, ожидает завершение чего-либо(например, завершения асинхронной операции).

- Решенный или Выполненный — Промис решен, если результат доступен. 

То есть, что-то завершило свое выполнение(например, асинхронная операция) и все прошло хорошо.

- Отклоненный — Промиc отклонен, если произошла ошибка в процессе выполнения.


# Создаем Промис


Синтаксис:

```
const promise = new Promise((resolve, reject) => {
    ...
});

```

Мы создали новый промис, используя конструктор Промисов, он принимает один аргумент, обратный вызов, также известный как исполнительная функция, которая принимает 2 обратных вызова, resolve и reject.

Исполнительная функция выполняется сразу же после создания промиса. 

Промис становится выполненным при помощи вызова resolve(), а отклоненным при помощи reject(). 

Например:

```
const promise = new Promise((resolve, reject) => {
  if(allWentWell) {
    resolve('Все прошло отлично!');
  } else {
    reject('Что-то пошло не так');
  }
});

```

resolve() и reject() принимают один аргумент, который может быть строкой, числом, логическим выражением, массивом или объектом.

```
const promise = new Promise((resolve, reject) => {
  const randomNumber = Math.random();
  setTimeout(() => {
    if(randomNumber < 0.6) {
      resolve('Все прошло отлично!');
    } else {
      reject('Что-то пошло не так');
    }
  }, 2000);
});

```

Здесь я создал новый промис используя конструктор Промисов. 

Промис выполняется или отклоняется через 2 секунды после его создания. 

Промис выполняется, если randomNumber меньше, чем .6 и отклоняется в остальных случаях.

Когда промис был создан, он будет в состоянии ожидания и его значение будет undefined.

![help](https://habrastorage.org/webt/cs/wr/c2/cswrc2jdrixhaguff2w9oijiyf4.png)

После 2 секунд таймер заканчивается, промис случайным образом либо выполняется, либо отклоняется, и его значением будет то, которое передано в функцию resolve или reject. 

Ниже пример двух случаев:


Успешное выполнение:

![help](https://habrastorage.org/webt/eq/3y/ss/eq3ysskatvuvjnvpoaz9k7zdmvi.png)

Отклонение промиса:

![help](https://habrastorage.org/webt/qn/7v/ee/qn7vee1ebi19qgo4zzv72tgpfjg.png)


# Использование Промиса

Теперь мы знаем как создавать промисы, давайте теперь разберемся как применять уже созданный промис. 

Мы используем промисы при помощи методов then() и catch().

# then

then принимает в себя 2 коллбэк функции:

- successCallback вызывается, если промис был успешно выполнен. Принимает один аргумент, который является значением переданным в resolve().

- failureCallback вызывается, если промис был отклонен. Принимает один аргумент, который является значением преданным в reject().

```
const promise = new Promise((resolve, reject) => {
  const randomNumber = Math.random();
  if(randomNumber < 0.7) {
    resolve('Все прошло отлично!');
  } else {
    reject(new Error('Что-то пошло не так'));
  }
});

promise.then(
  (data) => console.log(data), // вывести 'Все прошло отлично!'
  (error) => console.log(error), // вывести ошибку
);

```

Если промис был выполнен, то вызывается successCallback со значением, переданным в resolve(). 

И если промис был отклонен, то вызывается failureCallback со значением, переданным в reject().

# .catch()

Мы используем catch() для обработки ошибок. 

Это более читабельно, нежели обработка ошибок внутри failureCallback внутри обратного вызова метода then().

```
const promise = new Promise((resolve, reject) => {
  reject(new Error('Что-то пошло не так'));
});

promise
  .then((data) => {
     console.log(data);
   })
  .catch((error) => {
     console.log(error); // вывести ошибку
  });

```

# Цепочка промисов

```
const promise1 = new Promise((resolve, reject) => {
  resolve('Promise1 выполнен');
});

const promise2 = new Promise((resolve, reject) => {
  resolve('Promise2 выполнен');
});

const promise3 = new Promise((resolve, reject) => {
  reject('Promise3 отклонен');
});

promise1
  .then((data) => {
    console.log(data);  // Promise1 выполнен
    return promise2;
  })
  .then((data) => {
    console.log(data);  // Promise2 выполнен
    return promise3;
  })
  .then((data) => {
    console.log(data);
  })
  .catch((error) => {
    console.log(error);  // Promise3 отклонен
  });

```

# Promise.all( )

Этот метод берет массив промисов и возвращает новый промис, который будет выполненным, когда все промисы внутри массива выполнены или отклонен, как только встречается промис, который отклоняется. 

Например:


```
const promise1 = new Promise((resolve, reject) => {
 setTimeout(() => {
  resolve('Promise1 выполнен');
 }, 2000);
});

const promise2 = new Promise((resolve, reject) => {
 setTimeout(() => {
  resolve('Promise2 выполнен');
 }, 1500);
});

Promise.all([promise1, promise2])
  .then((data) => console.log(data[0], data[1])); // Promise1 выполнен Promise2 выполнен
  .catch((error) => console.log(error));

```

Промис отклоняется с причиной отклонения первого промиса в переданном массиве. Например:

```
const promise1 = new Promise((resolve, reject) => {
 setTimeout(() => {
  resolve('Promise1 выполнен');
 }, 2000);
});

const promise2 = new Promise((resolve, reject) => {
 setTimeout(() => {
  reject('Promise2 отклонен');
 }, 1500);
});

Promise.all([promise1, promise2])
  .then((data) => console.log(data[0], data[1]))
  .catch((error) => console.log(error));  // Promise2 отклонен

```


# Promise.race( )

Этот метод принимает массив промисов и возвращает один новый промис, который будет выполненным, как только встретится выполненный промис в массиве или же отклоняется, если отклоненный промис встречается раньше. 

Например:

```
const promise1 = new Promise((resolve, reject) => {
 setTimeout(() => {
  resolve('Promise1 выполнен');
 }, 1000);
});

const promise2 = new Promise((resolve, reject) => {
 setTimeout(() => {
  reject('Promise2 отклонен');
 }, 1500);
});

Promise.race([promise1, promise2])
  .then((data) => console.log(data))  // Promise1 выполнен
  .catch((error) => console.log(error));

```

Тут мы имеем два промиса, где один выполняется через 1 секунду, а другой отклоняется через 1.5 секунды. 

Как только первый промис выполнен, возвращенный из Promise.race() промис будет иметь статус выполненного не дожидаясь статуса второго промиса.

Здесь data, которая передается в then() является значением первого, выполненного, промиса.

# Прощай, XMLHttpRequest!

- fetch() позволяет вам делать запросы, схожие с XMLHttpRequest (XHR). 

Основное отличие заключается в том, что Fetch API использует Promises (Обещания), которые позволяют использовать более простое и чистое API, избегать катастрофического количества callback'ов и необходимости помнить API для XMLHttpRequest.

# XMLHttpRequest

Пример с XMLHttpRequest потребует от нас установить два обработчика событий на success и error, а так же вызвать два метода: open() и send().

```
function reqListener() {  
  var data = JSON.parse(this.responseText);  
  console.log(data);  
}

function reqError(err) {  
  console.log('Fetch Error :-S', err);  
}

var oReq = new XMLHttpRequest();
oReq.open('get', './api/some.json');  
oReq.send();
oReq.onload = reqListener;  
oReq.onerror = reqError;  

```

# Fetch

```
fetch('./api/some.json')  
  .then(  
    function(response) {  
      if (response.status !== 200) {  
        console.log('Looks like there was a problem. Status Code: ' +  
          response.status);  
        return;  
      }

      // Examine the text in the response  
      response.json().then(function(data) {  
        console.log(data);  
      });  
    }  
  )  
  .catch(function(err) {  
    console.log('Fetch Error :-S', err);  
  });

```

